server:
  port: 9090
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true


spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 1234
    hikari:
      idle-timeout: 10000
      maximum-pool-size: 10
      minimum-idle: 5
      pool-name: BaseikariPool
#    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
  jpa:
    show-sql: true
    properties:
      hibernate:
        use_sql_comments: true
        format_sql: true

#logging:
#  level:
#    p6psy: info
#    org.hibernate.type.descriptor.sql.BasicBinder: trace

#decorator:
#  datasource:
#    p6spy:
#      enable-logging: true